version: "3.4"
services:
  base-app:
    image: base-app
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "/app/scripts/nginx"
      - ".:/app"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    restart: always
    env_file:
      - .postgres_env
